[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sedaro"
version = "0.1.0"
authors = [
  { name="Sedaro", email="support@sedarotech.com" },
]
description = "A python client to interact with the Sedaro Satellite API."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License", # FIXME
    "Operating System :: OS Independent", # FIXME
    "Topic :: Software Development",
]

dependencies = [
  "sedaro_base_client @ file:///src/sedaro_base_client/dist/sedaro_base_client-1.0.0.tar.gz",
  "typing-extensions >= 4.3.0",
]

[project.urls]
"Homepage" = "https://gitlab.sedaro.com/sedaro-satellite/clients" # FIXME
"Bug Tracker" = "https://gitlab.sedaro.com/sedaro-satellite/clients" # FIXME