# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Test Python Package

on:
  push:
    branches: ['main', '2024-05-21-ci-pipeline'] # FIXME, change branches to just main
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.10', '3.9']
      # run only one at a time, becuase the tests run on the same branches, and they mess each other up in parallel
      max-parallel: 1

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Install local Sedaro package
        run: |
          pip install ./sedaro

      - name: Create config.py
        run: |
          echo "HOST = '${{ secrets.HOST }}'" >> tests/config.py
          echo "API_KEY = '${{ secrets.API_KEY }}'" >> tests/config.py
          echo "AUTH_HANDLE = '${{ secrets.AUTH_HANDLE }}'" >> tests/config.py

          echo "SIMPLESAT_A_T_ID = '${{ secrets.SIMPLESAT_A_T_ID }}'" >> tests/config.py
          echo "SIMPLESAT_SCENARIO_ID = '${{ secrets.SIMPLESAT_SCENARIO_ID }}'" >> tests/config.py
          echo "WILDFIRE_A_T_ID = '${{ secrets.WILDFIRE_A_T_ID }}'" >> tests/config.py
          echo "WILDFIRE_SCENARIO_ID = '${{ secrets.WILDFIRE_SCENARIO_ID }}'" >> tests/config.py

      - name: Test with pytest
        run: |
          pytest
